name: API Test Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
   - cron: 00 18 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute tests
      run: mvn clean test -Dtestng-file=testng
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: Logs
        path: logs/

